### ISSUE TITLE
[MacOS] App Notarising and Stapling

### ISSUE THREAD

**Issue by DhruvGovaniVH** [DhruvGovani/IssuesOverFlow#5]
Step 1 : Make a `.zip` of `.app` file
Step 2 : Add Apple ID Creds to Keychain.
```sh
xcrun notarytool store-credentials
```
Step 3 : Submit Your app to Apple Services
``` sh
xcrun notarytool submit yourapp.zip --keychain-profile "ProfileName" --webhook "https://example.com/notarization"
```
Step 4 : Download Log via the id of submission which you received from step 3
```sh
xcrun notarytool log fd10e3de-3055-4dc6-9df8-846294d0e3ba --keychain-profile "NFTTool" developer_log.json
```
Step 5 : Check the JSON file and verify if there are any issues or warning to take care of and app is ready to distribute
Step 6 : Now Unzip and Staple each item of the archive using below command
```
xcrun stapler staple yourapp.app
```
Step 7 : Now Verify the App is Notarised using below command
```
 spctl -a -vvv -t install yourapp.app
yourapp.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: DevName (#TeamID)
```

**Comment by smalin10** [comment]
@DhruvGovani, how can I get webhook and does profile needs to be created from scratch?
Also how can I integrate this into xcodebuild command?
Can you please provide an example?
